version: '3'
services:
#  gql:
#    build: .
##    image: prakharsrivastav/gql:9
#    ports:
#      - '8080:8080'


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411

networks:
  default:
    external:
      name: gql-server-nw