spring:
  application:
    name: gql-server
server:
  port: 8080
service:
  artist:
    host: artist-service
    port: 6565
  album:
    host: album-service
    port: 6565
  track:
    host: track-service
    port: 6565