apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gql-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gql-service
    spec:
      containers:
        - name: gql-service
          image: prakharsrivastav/gql:2
          ports:
            - name: http
              containerPort: 8080
